sonar.projectKey=PokesalProjeto
sonar.projectName=ProjetoDemonstrativo
sonar.host.url=http://localhost:9000
sonar.token=squ_ab2d94208f8a7425bd30f88120eb71d96acf2ce2
sonar.sources=src/main/java/com/ucsal
sonar.tests=src/test/java/com/ucsal
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/Main.java
sonar.coverage.exclusions=**/Main.java,**/EfeitosStatus.java